package cn.baibaisqt.domain;

/**
 * licai_user
 * 
 * @author xyh
 * @version 1.0.0 2022-01-12
 */
public class LicaiUser implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 1587826400419890134L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private String id;

    /** 账号 */
    private String uName;

    /** 密码 */
    private String uPassword;

    /** uTel */
    private String uTel;

    /** 头像 */
    private String uImg;

    /** 禁用 */
    private Integer uStop;

    /** 管理员 */
    private Integer uIsadmin;

    /** uEmail */
    private String uEmail;

    /** uDesc */
    private String uDesc;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     *          id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取账号
     * 
     * @return 账号
     */
    public String getUName() {
        return this.uName;
    }

    /**
     * 设置账号
     * 
     * @param uName
     *          账号
     */
    public void setUName(String uName) {
        this.uName = uName;
    }

    /**
     * 获取密码
     * 
     * @return 密码
     */
    public String getUPassword() {
        return this.uPassword;
    }

    /**
     * 设置密码
     * 
     * @param uPassword
     *          密码
     */
    public void setUPassword(String uPassword) {
        this.uPassword = uPassword;
    }

    /**
     * 获取uTel
     * 
     * @return uTel
     */
    public String getUTel() {
        return this.uTel;
    }

    /**
     * 设置uTel
     * 
     * @param uTel
     */
    public void setUTel(String uTel) {
        this.uTel = uTel;
    }

    /**
     * 获取头像
     * 
     * @return 头像
     */
    public String getUImg() {
        return this.uImg;
    }

    /**
     * 设置头像
     * 
     * @param uImg
     *          头像
     */
    public void setUImg(String uImg) {
        this.uImg = uImg;
    }

    /**
     * 获取禁用
     * 
     * @return 禁用
     */
    public Integer getUStop() {
        return this.uStop;
    }

    /**
     * 设置禁用
     * 
     * @param uStop
     *          禁用
     */
    public void setUStop(Integer uStop) {
        this.uStop = uStop;
    }

    /**
     * 获取管理员
     * 
     * @return 管理员
     */
    public Integer getUIsadmin() {
        return this.uIsadmin;
    }

    /**
     * 设置管理员
     * 
     * @param uIsadmin
     *          管理员
     */
    public void setUIsadmin(Integer uIsadmin) {
        this.uIsadmin = uIsadmin;
    }

    /**
     * 获取uEmail
     * 
     * @return uEmail
     */
    public String getUEmail() {
        return this.uEmail;
    }

    /**
     * 设置uEmail
     * 
     * @param uEmail
     */
    public void setUEmail(String uEmail) {
        this.uEmail = uEmail;
    }

    /**
     * 获取uDesc
     * 
     * @return uDesc
     */
    public String getUDesc() {
        return this.uDesc;
    }

    /**
     * 设置uDesc
     * 
     * @param uDesc
     */
    public void setUDesc(String uDesc) {
        this.uDesc = uDesc;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}