package cn.baibaisqt.domain;

import java.util.Date;

/**
 * licai_consume
 * 
 * @author xyh
 * @version 1.0.0 2022-01-12
 */
public class LicaiConsume implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 3424800860853281919L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private String id;

    /** 消费类型 */
    private String cType;

    /** cMoney */
    private Integer cMoney;

    /** cMaxMoney */
    private Integer cMaxMoney;

    /** cDate */
    private Date cDate;

    /** uId */
    private String uId;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取消费类型
     * 
     * @return 消费类型
     */
    public String getCType() {
        return this.cType;
    }

    /**
     * 设置消费类型
     * 
     * @param cType
     *          消费类型
     */
    public void setCType(String cType) {
        this.cType = cType;
    }

    /**
     * 获取cMoney
     * 
     * @return cMoney
     */
    public Integer getCMoney() {
        return this.cMoney;
    }

    /**
     * 设置cMoney
     * 
     * @param cMoney
     */
    public void setCMoney(Integer cMoney) {
        this.cMoney = cMoney;
    }

    /**
     * 获取cMaxMoney
     * 
     * @return cMaxMoney
     */
    public Integer getCMaxMoney() {
        return this.cMaxMoney;
    }

    /**
     * 设置cMaxMoney
     * 
     * @param cMaxMoney
     */
    public void setCMaxMoney(Integer cMaxMoney) {
        this.cMaxMoney = cMaxMoney;
    }

    /**
     * 获取cDate
     * 
     * @return cDate
     */
    public Date getCDate() {
        return this.cDate;
    }

    /**
     * 设置cDate
     * 
     * @param cDate
     */
    public void setCDate(Date cDate) {
        this.cDate = cDate;
    }

    /**
     * 获取uId
     * 
     * @return uId
     */
    public String getUId() {
        return this.uId;
    }

    /**
     * 设置uId
     * 
     * @param uId
     */
    public void setUId(String uId) {
        this.uId = uId;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}